project:
  type: website
  output-dir: docs  # Change this from _site to docs

website:
  title: "di4health.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://di4health.github.io/book
        text: Book 
      - href: programming.qmd
        text: Programming
      - href: resources.qmd
        text: Resources
      - href: team_skills.qmd
        text: Team skills

format:
  html:
    theme:
      - default
      - brand
    css: styles.css
    toc: true



